/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SearchRouteImport } from './routes/search'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminExportRouteImport } from './routes/admin.export'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as ApiPhotoRouteImport } from './routes/api/photo'
import { Route as ApiShopifyZipRouteImport } from './routes/api/shopify-zip'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as CollectionsIndexRouteImport } from './routes/collections/index'
import { Route as CollectionsHandleRouteImport } from './routes/collections/$handle'
import { Route as PagesAboutRouteImport } from './routes/pages/about'
import { Route as PagesAuthenticityRouteImport } from './routes/pages/authenticity'
import { Route as PagesContactRouteImport } from './routes/pages/contact'
import { Route as PagesPaymentRouteImport } from './routes/pages/payment'
import { Route as PagesReferRouteImport } from './routes/pages/refer'
import { Route as PagesReturnsRouteImport } from './routes/pages/returns'
import { Route as PagesShippingRouteImport } from './routes/pages/shipping'
import { Route as PagesShopifyRouteImport } from './routes/pages/shopify'
import { Route as ProductsHandleRouteImport } from './routes/products/$handle'
import { Route as AdminListingsIdRouteImport } from './routes/admin.listings.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExportRoute = AdminExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPhotoRoute = ApiPhotoRouteImport.update({
  id: '/api/photo',
  path: '/api/photo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopifyZipRoute = ApiShopifyZipRouteImport.update({
  id: '/api/shopify-zip',
  path: '/api/shopify-zip',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CheckoutRoute,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsHandleRoute = CollectionsHandleRouteImport.update({
  id: '/collections/$handle',
  path: '/collections/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesAboutRoute = PagesAboutRouteImport.update({
  id: '/pages/about',
  path: '/pages/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesAuthenticityRoute = PagesAuthenticityRouteImport.update({
  id: '/pages/authenticity',
  path: '/pages/authenticity',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesContactRoute = PagesContactRouteImport.update({
  id: '/pages/contact',
  path: '/pages/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesPaymentRoute = PagesPaymentRouteImport.update({
  id: '/pages/payment',
  path: '/pages/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesReferRoute = PagesReferRouteImport.update({
  id: '/pages/refer',
  path: '/pages/refer',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesReturnsRoute = PagesReturnsRouteImport.update({
  id: '/pages/returns',
  path: '/pages/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesShippingRoute = PagesShippingRouteImport.update({
  id: '/pages/shipping',
  path: '/pages/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesShopifyRoute = PagesShopifyRouteImport.update({
  id: '/pages/shopify',
  path: '/pages/shopify',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsHandleRoute = ProductsHandleRouteImport.update({
  id: '/products/$handle',
  path: '/products/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminListingsIdRoute = AdminListingsIdRouteImport.update({
  id: '/listings/$id',
  path: '/listings/$id',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/wishlist': typeof WishlistRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/security': typeof AdminSecurityRoute
  '/api/photo': typeof ApiPhotoRoute
  '/api/shopify-zip': typeof ApiShopifyZipRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/pages/about': typeof PagesAboutRoute
  '/pages/authenticity': typeof PagesAuthenticityRoute
  '/pages/contact': typeof PagesContactRoute
  '/pages/payment': typeof PagesPaymentRoute
  '/pages/refer': typeof PagesReferRoute
  '/pages/returns': typeof PagesReturnsRoute
  '/pages/shipping': typeof PagesShippingRoute
  '/pages/shopify': typeof PagesShopifyRoute
  '/products/$handle': typeof ProductsHandleRoute
  '/admin/': typeof AdminIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/admin/listings/$id': typeof AdminListingsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/wishlist': typeof WishlistRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/security': typeof AdminSecurityRoute
  '/api/photo': typeof ApiPhotoRoute
  '/api/shopify-zip': typeof ApiShopifyZipRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/pages/about': typeof PagesAboutRoute
  '/pages/authenticity': typeof PagesAuthenticityRoute
  '/pages/contact': typeof PagesContactRoute
  '/pages/payment': typeof PagesPaymentRoute
  '/pages/refer': typeof PagesReferRoute
  '/pages/returns': typeof PagesReturnsRoute
  '/pages/shipping': typeof PagesShippingRoute
  '/pages/shopify': typeof PagesShopifyRoute
  '/products/$handle': typeof ProductsHandleRoute
  '/admin': typeof AdminIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/admin/listings/$id': typeof AdminListingsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/wishlist': typeof WishlistRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/security': typeof AdminSecurityRoute
  '/api/photo': typeof ApiPhotoRoute
  '/api/shopify-zip': typeof ApiShopifyZipRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/pages/about': typeof PagesAboutRoute
  '/pages/authenticity': typeof PagesAuthenticityRoute
  '/pages/contact': typeof PagesContactRoute
  '/pages/payment': typeof PagesPaymentRoute
  '/pages/refer': typeof PagesReferRoute
  '/pages/returns': typeof PagesReturnsRoute
  '/pages/shipping': typeof PagesShippingRoute
  '/pages/shopify': typeof PagesShopifyRoute
  '/products/$handle': typeof ProductsHandleRoute
  '/admin/': typeof AdminIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/admin/listings/$id': typeof AdminListingsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/search'
    | '/wishlist'
    | '/admin/export'
    | '/admin/inventory'
    | '/admin/security'
    | '/api/photo'
    | '/api/shopify-zip'
    | '/checkout/success'
    | '/collections/$handle'
    | '/pages/about'
    | '/pages/authenticity'
    | '/pages/contact'
    | '/pages/payment'
    | '/pages/refer'
    | '/pages/returns'
    | '/pages/shipping'
    | '/pages/shopify'
    | '/products/$handle'
    | '/admin/'
    | '/collections/'
    | '/admin/listings/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/search'
    | '/wishlist'
    | '/admin/export'
    | '/admin/inventory'
    | '/admin/security'
    | '/api/photo'
    | '/api/shopify-zip'
    | '/checkout/success'
    | '/collections/$handle'
    | '/pages/about'
    | '/pages/authenticity'
    | '/pages/contact'
    | '/pages/payment'
    | '/pages/refer'
    | '/pages/returns'
    | '/pages/shipping'
    | '/pages/shopify'
    | '/products/$handle'
    | '/admin'
    | '/collections'
    | '/admin/listings/$id'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/search'
    | '/wishlist'
    | '/admin/export'
    | '/admin/inventory'
    | '/admin/security'
    | '/api/photo'
    | '/api/shopify-zip'
    | '/checkout/success'
    | '/collections/$handle'
    | '/pages/about'
    | '/pages/authenticity'
    | '/pages/contact'
    | '/pages/payment'
    | '/pages/refer'
    | '/pages/returns'
    | '/pages/shipping'
    | '/pages/shopify'
    | '/products/$handle'
    | '/admin/'
    | '/collections/'
    | '/admin/listings/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  SearchRoute: typeof SearchRoute
  WishlistRoute: typeof WishlistRoute
  ApiPhotoRoute: typeof ApiPhotoRoute
  ApiShopifyZipRoute: typeof ApiShopifyZipRoute
  CollectionsHandleRoute: typeof CollectionsHandleRoute
  PagesAboutRoute: typeof PagesAboutRoute
  PagesAuthenticityRoute: typeof PagesAuthenticityRoute
  PagesContactRoute: typeof PagesContactRoute
  PagesPaymentRoute: typeof PagesPaymentRoute
  PagesReferRoute: typeof PagesReferRoute
  PagesReturnsRoute: typeof PagesReturnsRoute
  PagesShippingRoute: typeof PagesShippingRoute
  PagesShopifyRoute: typeof PagesShopifyRoute
  ProductsHandleRoute: typeof ProductsHandleRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/export': {
      id: '/admin/export'
      path: '/export'
      fullPath: '/admin/export'
      preLoaderRoute: typeof AdminExportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/photo': {
      id: '/api/photo'
      path: '/api/photo'
      fullPath: '/api/photo'
      preLoaderRoute: typeof ApiPhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shopify-zip': {
      id: '/api/shopify-zip'
      path: '/api/shopify-zip'
      fullPath: '/api/shopify-zip'
      preLoaderRoute: typeof ApiShopifyZipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$handle': {
      id: '/collections/$handle'
      path: '/collections/$handle'
      fullPath: '/collections/$handle'
      preLoaderRoute: typeof CollectionsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/about': {
      id: '/pages/about'
      path: '/pages/about'
      fullPath: '/pages/about'
      preLoaderRoute: typeof PagesAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/authenticity': {
      id: '/pages/authenticity'
      path: '/pages/authenticity'
      fullPath: '/pages/authenticity'
      preLoaderRoute: typeof PagesAuthenticityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/contact': {
      id: '/pages/contact'
      path: '/pages/contact'
      fullPath: '/pages/contact'
      preLoaderRoute: typeof PagesContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/payment': {
      id: '/pages/payment'
      path: '/pages/payment'
      fullPath: '/pages/payment'
      preLoaderRoute: typeof PagesPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/refer': {
      id: '/pages/refer'
      path: '/pages/refer'
      fullPath: '/pages/refer'
      preLoaderRoute: typeof PagesReferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/returns': {
      id: '/pages/returns'
      path: '/pages/returns'
      fullPath: '/pages/returns'
      preLoaderRoute: typeof PagesReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/shipping': {
      id: '/pages/shipping'
      path: '/pages/shipping'
      fullPath: '/pages/shipping'
      preLoaderRoute: typeof PagesShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/shopify': {
      id: '/pages/shopify'
      path: '/pages/shopify'
      fullPath: '/pages/shopify'
      preLoaderRoute: typeof PagesShopifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$handle': {
      id: '/products/$handle'
      path: '/products/$handle'
      fullPath: '/products/$handle'
      preLoaderRoute: typeof ProductsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/listings/$id': {
      id: '/admin/listings/$id'
      path: '/listings/$id'
      fullPath: '/admin/listings/$id'
      preLoaderRoute: typeof AdminListingsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminExportRoute: typeof AdminExportRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminListingsIdRoute: typeof AdminListingsIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminExportRoute: AdminExportRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminListingsIdRoute: AdminListingsIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CheckoutRouteChildren {
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutSuccessRoute: CheckoutSuccessRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  LoginRoute: LoginRoute,
  SearchRoute: SearchRoute,
  WishlistRoute: WishlistRoute,
  ApiPhotoRoute: ApiPhotoRoute,
  ApiShopifyZipRoute: ApiShopifyZipRoute,
  CollectionsHandleRoute: CollectionsHandleRoute,
  PagesAboutRoute: PagesAboutRoute,
  PagesAuthenticityRoute: PagesAuthenticityRoute,
  PagesContactRoute: PagesContactRoute,
  PagesPaymentRoute: PagesPaymentRoute,
  PagesReferRoute: PagesReferRoute,
  PagesReturnsRoute: PagesReturnsRoute,
  PagesShippingRoute: PagesShippingRoute,
  PagesShopifyRoute: PagesShopifyRoute,
  ProductsHandleRoute: ProductsHandleRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
